[package]
name = "defi-app"
version = "1.0.0"
authors = ["Your Name"]

[addresses]
MyModule = "0x3cb46d6b568346a3cf0411e9e38465822e31db4692be99d37de487d61df8f6cc"

[dev-addresses]
MyModule = "0x3cb46d6b568346a3cf0411e9e38465822e31db4692be99d37de487d61df8f6cc"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]


